# Generated by Django 4.2.7 on 2025-05-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events_images/no_event.png', null=True, upload_to='media/events_images/'),
        ),
    ]
