# Generated by Django 4.2.7 on 2025-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='no_event.png', null=True, upload_to='media/events_images/'),
        ),
    ]
