services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rqworker:  
    build: .
    command: python manage.py rqworker default
    depends_on:
      - redis
    volumes:
      - .:/app

volumes:
  redis_data: