# Generated by Django 4.2.7 on 2025-05-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='product_images/no_product.png', null=True, upload_to='services_images/'),
        ),
    ]
