# Generated by Django 4.2.7 on 2025-05-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='services_images/no_service.png', null=True, upload_to='media/services_images/'),
        ),
    ]
