# Generated by Django 4.2.7 on 2025-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='no_service.png', null=True, upload_to='media/services_images/'),
        ),
    ]
