# Generated by Django 5.2 on 2025-05-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(2, 'Confirmed'), (-1, 'Cancelled')], default=2),
        ),
    ]
