# Generated by Django 4.2.7 on 2025-05-17 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='barber',
            field=models.ForeignKey(default=1, limit_choices_to={'profile__role': 'W'}, on_delete=django.db.models.deletion.CASCADE, related_name='barber_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Barbero'),
            preserve_default=False,
        ),
    ]
