# Generated by Django 4.2.7 on 2025-05-19 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0004_booking_barber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('barber', 'date', 'time_slot')},
        ),
    ]
