# Generated by Django 4.2.7 on 2025-05-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
