# Generated by Django 5.2 on 2025-05-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
