# Generated by Django 4.2.7 on 2025-05-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_shoppingcartitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/no_product.png', null=True, upload_to='media/product_images/'),
        ),
    ]
